#!/usr/bin/env python3
"""Inventory a documentation source tree for a structural audit.

Walks a docs directory, emits one TSV row per page with the facts a mode
classification needs, and optionally compares the file tree against a
navigation config to surface orphans and dead nav entries.

Usage:
    docs-inventory.py <docs-dir> [--nav <config-file> ...] [--format tsv|json]
                      [--ext .md,.mdx,.rst] [--min-words N]

Columns: path, title, words, headings, max_heading_depth, code_blocks,
numbered_steps, imperatives, option_table, questions, internal_links,
external_links, in_nav, last_modified.

The nav comparison is deliberately heuristic: it pulls path-like strings out
of any config format (yaml, js, ts, json, md) and matches them against the
inventory by stem, so it works for MkDocs, Docusaurus, VitePress, Mintlify,
Starlight, Nextra, GitBook and Sphinx without a parser per generator. Treat
its orphan list as candidates to confirm, not as verdicts.
"""

import argparse
import json
import os
import re
import subprocess
import sys

FENCE = re.compile(r"^\s*(```|~~~|\.\. code-block::)")
ATX = re.compile(r"^(#{1,6})\s+(.+?)\s*#*$")
RST_TITLE = re.compile(r"^[=\-~^\"']{3,}\s*$")
NUMBERED = re.compile(r"^\s*(\d+[.)]\s+|[-*]\s+\d+[.)]\s+)")
IMPERATIVE = re.compile(
    r"^\s*(?:\d+[.)]\s*)?(Run|Install|Open|Click|Create|Add|Set|Copy|Paste|Navigate|"
    r"Deploy|Configure|Replace|Select|Enter|Start|Stop|Download|Import|Export|Update)\b"
)
TABLE_ROW = re.compile(r"^\s*\|.*\|\s*$")
OPTION_WORDS = re.compile(
    r"\b(parameter|argument|option|flag|field|property|returns?|type|default|required)\b", re.I
)
LINK = re.compile(r"\]\(([^)]+)\)")
NAV_PATH = re.compile(r"[\"'`]?([\w./-]+(?:/[\w.-]+)*)[\"'`]?")


def read(path):
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        return handle.read()


def title_of(lines, path):
    for index, line in enumerate(lines):
        match = ATX.match(line)
        if match:
            return match.group(2).strip()
        # reStructuredText: a line underlined by punctuation is a title.
        if index + 1 < len(lines) and line.strip() and RST_TITLE.match(lines[index + 1]):
            return line.strip()
    return os.path.splitext(os.path.basename(path))[0]


def last_modified(path, root):
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%as", "--", path],
            cwd=root, capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def analyse(path, root):
    text = read(path)
    lines = text.splitlines()
    stats = {
        "path": os.path.relpath(path, root),
        "title": title_of(lines, path),
        "words": 0, "headings": 0, "max_heading_depth": 0, "code_blocks": 0,
        "numbered_steps": 0, "imperatives": 0, "option_table": 0, "questions": 0,
        "internal_links": 0, "external_links": 0,
    }
    in_code = False
    table_rows = 0
    for line in lines:
        if FENCE.match(line):
            in_code = not in_code
            if in_code:
                stats["code_blocks"] += 1
            continue
        if in_code:
            continue
        stats["words"] += len(line.split())
        heading = ATX.match(line)
        if heading:
            depth = len(heading.group(1))
            stats["headings"] += 1
            stats["max_heading_depth"] = max(stats["max_heading_depth"], depth)
            if heading.group(2).rstrip().endswith("?"):
                stats["questions"] += 1
        if NUMBERED.match(line):
            stats["numbered_steps"] += 1
        if IMPERATIVE.match(line):
            stats["imperatives"] += 1
        if TABLE_ROW.match(line):
            table_rows += 1
            if OPTION_WORDS.search(line):
                stats["option_table"] = 1
        for target in LINK.findall(line):
            if target.startswith(("http://", "https://")):
                stats["external_links"] += 1
            elif not target.startswith("#"):
                stats["internal_links"] += 1
    # A long table without option vocabulary is still reference-shaped material.
    if table_rows >= 6:
        stats["option_table"] = 1
    stats["last_modified"] = last_modified(path, root)
    return stats


def nav_references(nav_files):
    """Return (page refs, section prefixes) found in navigation configs.

    A token written as `user-guide/` covers every page below it (MkDocs and
    Sphinx globs, Docusaurus autogenerated sidebars), so it is kept apart from
    exact page references and matched as a prefix.
    """
    refs, prefixes = set(), set()
    for nav in nav_files:
        for token in NAV_PATH.findall(read(nav)):
            if not ("/" in token or token.endswith((".md", ".mdx", ".rst"))):
                continue
            cleaned = os.path.splitext(token.strip("./"))[0].lower()
            if not cleaned:
                continue
            if token.rstrip("\"'`").endswith("/") or token.endswith("*"):
                prefixes.add(cleaned.rstrip("*/"))
            else:
                refs.add(cleaned)
    return refs, prefixes


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("docs_dir")
    parser.add_argument("--nav", action="append", default=[], help="navigation config file (repeatable)")
    parser.add_argument("--ext", default=".md,.mdx,.rst")
    parser.add_argument("--min-words", type=int, default=0, help="skip pages shorter than N words")
    parser.add_argument("--format", choices=["tsv", "json"], default="tsv")
    args = parser.parse_args()

    root = os.path.abspath(args.docs_dir)
    if not os.path.isdir(root):
        sys.exit(f"not a directory: {root}")
    extensions = tuple(e if e.startswith(".") else "." + e for e in args.ext.split(","))
    skip = {".git", "node_modules", "build", "dist", ".venv", "__pycache__", "_build", "site"}

    pages = []
    for base, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in skip and not d.startswith(".")]
        for name in sorted(files):
            if name.endswith(extensions):
                pages.append(analyse(os.path.join(base, name), root))
    pages = [p for p in pages if p["words"] >= args.min_words]

    refs, prefixes = nav_references(args.nav) if args.nav else (set(), set())
    for page in pages:
        stem = os.path.splitext(page["path"])[0].lower()
        listed = any(
            stem == r or stem.endswith("/" + r) or r.endswith("/" + stem) or
            (os.path.basename(stem) == "index" and os.path.dirname(stem) == r)
            for r in refs
        ) or any(stem.startswith(p + "/") for p in prefixes)
        page["in_nav"] = "" if not (refs or prefixes) else ("yes" if listed else "no")

    if args.format == "json":
        print(json.dumps(pages, indent=2))
        return

    columns = ["path", "title", "words", "headings", "max_heading_depth", "code_blocks",
               "numbered_steps", "imperatives", "option_table", "questions",
               "internal_links", "external_links", "in_nav", "last_modified"]
    print("\t".join(columns))
    for page in pages:
        print("\t".join(str(page.get(c, "")) for c in columns))
    orphans = [p["path"] for p in pages if p.get("in_nav") == "no"]
    if refs or prefixes:
        print(f"\n# pages: {len(pages)}\t# nav entries: {len(refs) + len(prefixes)}\t# orphan candidates: {len(orphans)}",
              file=sys.stderr)
        for path in orphans:
            print(f"orphan-candidate\t{path}", file=sys.stderr)


if __name__ == "__main__":
    main()
